name = "oas"
version = "6.1.0"
target = "javascript"
description = "Work with Open API Specs (previously swagger) and JSON Schema"
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "oas" }
links = []

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_http = ">= 3.7.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
non_empty_list = ">= 2.1.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
