name = "oas"
version = "2.1.1"
target = "javascript"
description = "Parse an open api (previously swagger) spec."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "oas" }
links = []

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.7.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
