name = "mcp_gen"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
oas = { path = ".." }
simplifile = ">= 2.3.0 and < 3.0.0"
# oas_generator = ">= 1.6.3 and < 2.0.0"
oas_generator = { path = "../../oas_generator" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
